Fix hacluster tests
Tidy up hacluster tests. In the process this fixes the error:

```
UnboundLocalError: local variable 'primary_status' referenced before assignment
```

This was caused by libjuju now returning an empty dict rather than
None when listing a subordinates units.