Bump up flake8
Fixes `AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'`

(cherry picked from commit fd65705445325e84774be96bdd265d5dd5f0fadb)