Remove broken functional test folder
Rationale:

1. `tox.ini` doesn't have a `func` target so probably these tests haven't
   been run for a long time.

2. These tests can't be run at the moment because of conflicting version
   ranges in python deps pulled via `requirements.txt` and `setup.py`, e.g.

   error: PyYAML 3.13 is installed but pyyaml<=6.0,>=5.1.2 is required by
          {'juju'}
   error: python-keystoneclient 3.21.0 is installed but
          python-keystoneclient>=3.22.0 is required by
          {'python-openstackclient'}

3. These tests don't have expectations. They just deploy a bundle.